#!/usr/bin/env python3

import sys
from PyQt5 import Qt

from src.MainWindow import MainWindow


if __name__ == '__main__':
    app = Qt.QApplication(sys.argv)
    win = MainWindow()
    win.show()
    sys.exit(app.exec_())
